--캠핑장테이블 생성
CREATE TABLE CAMP(
  CNO CHAR(3) PRIMARY KEY NOT NULL,
  CNAME VARCHAR(100) NOT NULL,
  JUSO VARCHAR(500),
  TEL VARCHAR(20)
);

INSERT INTO CAMP(CNO, CNAME, JUSO, TEL)
VALUES('100', '도토리캠핑장', '강원도', '010-1010-1010');
INSERT INTO CAMP(CNO, CNAME, JUSO, TEL)
VALUES('101', '솔밭캠핑장', '경기도', '010-1010-2020');
INSERT INTO CAMP(CNO, CNAME, JUSO, TEL)
VALUES('102', '하늘캠핑장', '인천', '010-1010-3030');
SELECT * FROM CAMP;

--시설물 테이블
CREATE TABLE FACIL(
  FNO INT PRIMARY KEY NOT NULL,
  FNAME VARCHAR(100) NOT NULL
);
INSERT INTO FACIL VALUES(0,'전기');
INSERT INTO FACIL VALUES(1,'수도');
INSERT INTO FACIL VALUES(2,'와이파이');
INSERT INTO FACIL VALUES(3,'화장실');
INSERT INTO FACIL VALUES(4,'수영장');
SELECT * FROM FACIL;

--타입 테이블
CREATE TABLE TYPE(
  TNO INT PRIMARY KEY NOT NULL,
  TNAME VARCHAR(100) NOT NULL
);
INSERT INTO TYPE VALUES(0, '카라반');
INSERT INTO TYPE VALUES(1, '글램핑');
INSERT INTO TYPE VALUES(2, '오토캠핑');
INSERT INTO TYPE VALUES(3, '펜션');
SELECT * FROM TYPE;

--캠핑장별 시설물
CREATE TABLE CAMP_FACIL(
  CNO CHAR(3) NOT NULL,
  FNO INT NOT NULL,
  PRIMARY KEY(CNO, FNO),
  FOREIGN KEY(CNO) REFERENCES CAMP(CNO),
  FOREIGN KEY(FNO) REFERENCES FACIL(FNO)
);  
  
--캠핑장별 타일
CREATE TABLE CAMP_TYPE(
  CNO CHAR(3) NOT NULL,
  TNO INT NOT NULL,
  PRIMARY KEY(CNO, TNO),
  FOREIGN KEY(CNO) REFERENCES CAMP(CNO),
  FOREIGN KEY(TNO) REFERENCES TYPE(TNO)
); 