-- 사용자테이블
CREATE TABLE USERS(
  ID VARCHAR(20) NOT NULL PRIMARY KEY,
  UNAME VARCHAR(20) NOT NULL,
  POINT INT DEFAULT 0,
  PHONE VARCHAR(20)
);

DESC USERS;

-- 메시지테이블
CREATE TABLE MESSAGES(
  MID INT NOT NULL PRIMARY KEY,
  SENDER VARCHAR(20) NOT NULL,
  RECEIVER VARCHAR(20) NOT NULL,
  SDATE DATE DEFAULT SYSDATE,
  MESSAGE VARCHAR(1000) NOT NULL,
  FOREIGN KEY(SENDER) REFERENCES USERS(ID),
  FOREIGN KEY(RECEIVER) REFERENCES USERS(ID)
);

-- 사용자 입력
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('blue','이블루',20,'010-1010-1010');
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('red','박레드',10,'010-2020-2020');
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('green','최그린',10,'010-3030-3030');

SELECT * FROM USERS;

-- 메시지번호 시퀀스생성
CREATE SEQUENCE SEQ_MID START WITH 1 INCREMENT BY 1;

-- 메시지 입력
INSERT INTO MESSAGES(MID,SENDER,RECEIVER,SDATE,MESSAGE)
VALUES(SEQ_MID.NEXTVAL,'blue','red',SYSDATE,'레드야 잘 지내지?');
INSERT INTO MESSAGES(MID,SENDER,RECEIVER,SDATE,MESSAGE)
VALUES(SEQ_MID.NEXTVAL,'red','blue',SYSDATE,'블루야 오랜만');
INSERT INTO MESSAGES(MID,SENDER,RECEIVER,SDATE,MESSAGE)
VALUES(SEQ_MID.NEXTVAL,'green','blue',SYSDATE,'감기 조심해');
INSERT INTO MESSAGES(MID,SENDER,RECEIVER,SDATE,MESSAGE)
VALUES(SEQ_MID.NEXTVAL,'blue','green',SYSDATE,'고마워 조심할게');

SELECT * FROM MESSAGES;

-- 블루가 보낸 메시지
SELECT M.*, U.UNAME, U.PHONE 
FROM MESSAGES M, USERS U 
WHERE SENDER='blue'
AND M.RECEIVER = U.ID;

-- 블루가 받은 메시지
SELECT M.*, UNAME, PHONE 
FROM MESSAGES M, USERS U 
WHERE RECEIVER='blue'
AND SENDER = ID
AND SDEL = 0;

COMMIT;

SELECT * FROM MESSAGES;

ALTER TABLE MESSAGES ADD RDEL INT DEFAULT 0;